Parameters:
  SiteHostName:
    Type: String
    Default: www
    Description: |
      The "hostname" portion of the URL for the S3 Static Site you are
      creating.  For example, if you were creating the site
      www.example.com, the hostname portion is www.
  SiteDomainName:
    Type: String
    Default: example.com
    Description: |
      The "domain name" portion of the URL for the S3 Static Site you are
      creating.  For example, if you were creating the site
      www.example.com, the domain name portion is example.com.  The domain
      name should NOT end in a period.
  CertArn:
    Type: String
    Description: |
      The ARN for the ACM Certificate to be used on this site's Cloudfront
      distribution.

Mappings:
  RegionMap:
    us-east-2:
      S3hostedzoneID: Z2O1EMRO9K5GLX
      websiteendpoint: s3-website.us-east-2.amazonaws.com
    us-east-1:
      S3hostedzoneID: Z3AQBSTGFYJSTF
      websiteendpoint: s3-website-us-east-1.amazonaws.com
    us-west-1:
      S3hostedzoneID: Z2F56UZL2M1ACD
      websiteendpoint: s3-website-us-west-1.amazonaws.com
    us-west-2:
      S3hostedzoneID: Z3BJ6K6RIION7M
      websiteendpoint: s3-website-us-west-2.amazonaws.com
    ca-central-1:
      S3hostedzoneID: Z1QDHH18159H29
      websiteendpoint: s3-website.ca-central-1.amazonaws.com
    ap-south-1:
      S3hostedzoneID: Z11RGJOFQNVJUP
      websiteendpoint: s3-website.ap-south-1.amazonaws.com
    ap-northeast-2:
      S3hostedzoneID: Z3W03O7B5YMIYP
      websiteendpoint: s3-website.ap-northeast-2.amazonaws.com
    ap-southeast-1:
      S3hostedzoneID: Z3O0J2DXBE1FTB
      websiteendpoint: s3-website-ap-southeast-1.amazonaws.com
    ap-southeast-2:
      S3hostedzoneID: Z1WCIGYICN2BYD
      websiteendpoint: s3-website-ap-southeast-2.amazonaws.com
    ap-northeast-1:
      S3hostedzoneID: Z2M4EHUR26P7ZW
      websiteendpoint: s3-website-ap-northeast-1.amazonaws.com
    eu-central-1:
      S3hostedzoneID: Z21DNDUVLTQW6Q
      websiteendpoint: s3-website.eu-central-1.amazonaws.com
    eu-west-1:
      S3hostedzoneID: Z1BKCTXD74EZPE
      websiteendpoint: s3-website-eu-west-1.amazonaws.com
    eu-west-2:
      S3hostedzoneID: Z3GKZC51ZF0DB4
      websiteendpoint: s3-website.eu-west-2.amazonaws.com
    sa-east-1:
      S3hostedzoneID: Z7KQH4QJS55SO
      websiteendpoint: s3-website-sa-east-1.amazonaws.com

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '.', [ !Ref SiteHostName, !Ref SiteDomainName ] ]
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  SiteDns:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub "${SiteDomainName}."
      RecordSets:
        -
          Name: !Sub "${SiteHostName}.${SiteDomainName}"
          Type: A
          AliasTarget:
            DNSName: !GetAtt SiteDistribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2

  SiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          -
            DomainName: !Sub "${SiteHostName}.${SiteDomainName}.s3-website.${AWS::Region}.amazonaws.com"
            Id: !Sub "${SiteHostName}.${SiteDomainName}-S3BucketUrl"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - !Sub "${SiteHostName}.${SiteDomainName}"
        ViewerCertificate:
          AcmCertificateArn: !Ref CertArn
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          AllowedMethods:
            - OPTIONS
            - HEAD
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH
          TargetOriginId: !Sub "${SiteHostName}.${SiteDomainName}-S3BucketUrl"
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https



Outputs:
  BucketName:
    Value: !Ref SiteBucket
