Parameters:
  SiteHostName:
    Type: String
    Default: www
    Description: |
      The "hostname" portion of the URL for the S3 Static Site you are
      creating.  For example, if you were creating the site
      www.example.com, the hostname portion is www.
  SiteDomainName:
    Type: String
    Default: example.com
    Description: |
      The "domain name" portion of the URL for the S3 Static Site you are
      creating.  For example, if you were creating the site
      www.example.com, the domain name portion is example.com.  The domain
      name should NOT end in a period.
  CertArn:
    Type: String
    Description: |
      The ARN for the ACM Certificate to be used on this site's Cloudfront
      distribution.
  DefaultTTL:
    Type: Number
    Default: 15
    Description: |
      The default TTL, in seconds, for items in the CloudFront cache
      that do not have cache header information.  The default is set
      low, under the assumption you will be developing your site.
      Once in production, you should increase this value apropriately
      (such as the AWS default of 86400).
  PriceClass:
    Type: String
    AllowedValues: [ "ALL", "100", "200" ]
    Default: "100"
    ConstraintDescription: |
      Allowed values are 100, 200, and ALL.
    Description: |
      100: Use Only US, Canada and Europe
      200: Use Only US, Canada, Europe, and Asia
      ALL: Use All Edge Locations (Best Performance)


Mappings:
  RegionMap:
    us-east-2:
      S3hostedzoneID: Z2O1EMRO9K5GLX
      websiteendpoint: s3-website.us-east-2.amazonaws.com
    us-east-1:
      S3hostedzoneID: Z3AQBSTGFYJSTF
      websiteendpoint: s3-website-us-east-1.amazonaws.com
    us-west-1:
      S3hostedzoneID: Z2F56UZL2M1ACD
      websiteendpoint: s3-website-us-west-1.amazonaws.com
    us-west-2:
      S3hostedzoneID: Z3BJ6K6RIION7M
      websiteendpoint: s3-website-us-west-2.amazonaws.com
    ca-central-1:
      S3hostedzoneID: Z1QDHH18159H29
      websiteendpoint: s3-website.ca-central-1.amazonaws.com
    ap-south-1:
      S3hostedzoneID: Z11RGJOFQNVJUP
      websiteendpoint: s3-website.ap-south-1.amazonaws.com
    ap-northeast-2:
      S3hostedzoneID: Z3W03O7B5YMIYP
      websiteendpoint: s3-website.ap-northeast-2.amazonaws.com
    ap-southeast-1:
      S3hostedzoneID: Z3O0J2DXBE1FTB
      websiteendpoint: s3-website-ap-southeast-1.amazonaws.com
    ap-southeast-2:
      S3hostedzoneID: Z1WCIGYICN2BYD
      websiteendpoint: s3-website-ap-southeast-2.amazonaws.com
    ap-northeast-1:
      S3hostedzoneID: Z2M4EHUR26P7ZW
      websiteendpoint: s3-website-ap-northeast-1.amazonaws.com
    eu-central-1:
      S3hostedzoneID: Z21DNDUVLTQW6Q
      websiteendpoint: s3-website.eu-central-1.amazonaws.com
    eu-west-1:
      S3hostedzoneID: Z1BKCTXD74EZPE
      websiteendpoint: s3-website-eu-west-1.amazonaws.com
    eu-west-2:
      S3hostedzoneID: Z3GKZC51ZF0DB4
      websiteendpoint: s3-website.eu-west-2.amazonaws.com
    sa-east-1:
      S3hostedzoneID: Z7KQH4QJS55SO
      websiteendpoint: s3-website-sa-east-1.amazonaws.com

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '.', [ !Ref SiteHostName, !Ref SiteDomainName ] ]
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  SiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource:
                - !Sub "arn:aws:s3:::${SiteHostName}.${SiteDomainName}/*"


  SiteDns:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub "${SiteDomainName}."
      RecordSets:
        -
          Name: !Sub "${SiteHostName}.${SiteDomainName}"
          Type: A
          AliasTarget:
            DNSName: !GetAtt SiteDistribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2

  SiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass: !Sub "PriceClass_${PriceClass}"
        Origins:
          -
            DomainName: !Sub "${SiteHostName}.${SiteDomainName}.s3-website.${AWS::Region}.amazonaws.com"
            Id: !Sub "${SiteHostName}.${SiteDomainName}-S3BucketUrl"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - !Sub "${SiteHostName}.${SiteDomainName}"
        ViewerCertificate:
          AcmCertificateArn: !Ref CertArn
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          DefaultTTL: !Ref DefaultTTL
          AllowedMethods:
            - OPTIONS
            - HEAD
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH
          TargetOriginId: !Sub "${SiteHostName}.${SiteDomainName}-S3BucketUrl"
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https



Outputs:
  BucketName:
    Value: !Ref SiteBucket
